### ISSUE TITLE
Exact computation of the row echelon form

### ISSUE THREAD

**Issue by blegat** [kalmarek/SymbolicWedderburn.jl#23]
We currently use floating arithmetic for doing the row echelon form that might create numerical rounding error, we could have an option to use exact arithmetic.

**Comment by kalmarek** [comment]
should be addressed by 4026bed

You may ask for the exact version by calling `symmetry_adapted_basis(Rational{BigInt}, G, ...)`, or for a float one by `symmetry_adapted_basis(Float64, G, ...)`.
Both will give you blocks of `Cyclotomic`s (with coeffs in `Rational{BigInt}`, or `Float64`s), so you will need to convert these to actual `Rational{BigInt}`s or `Float64`s by yourself. Note that the latter conversion may fail since `Cyclotomic`s represent algebraic numbers, which may be real, but irrational.

**Comment by blegat** [comment]
Excellent! Yes, converting from `Cyclotomic{Rational{BigInt}}` to `Rational{BigInt}` may be hopeless but we could convert it to `Float64`, `BigFloat`, ... with I assume less rounding errors that if the row echelon was done in floating point arithmetic too.
