### ISSUE TITLE
Include pointers in docstring

### ISSUE THREAD

**Issue by blegat** [kalmarek/SymbolicWedderburn.jl#26]
It would be helpful to give pointers to references with more details on the algorithms used in this package.
For instance, in the docstrings of

- [ ] `isotypical_basis`
- [ ] `matrix_projection`

**Comment by kalmarek** [comment]
I don't think there's much to add here. There aren't really any advanced algorithms involved.

If `π: G → GL(n,K)` is a matrix representation, then this homomorphism has canonical extension to a homomorphism of  group algebra into the algebra `M(n,n,K)` of matrices over `K`. The `matrix_projection` (probably not a great name) is just realization of this extension. If `χ:G → K` is a function on the group (e.g. a character) (often written as `Σ χ(g)·g`), then `matrix_projection` is just `Σ χ(g)·π(g)`, a weighted sum of matrices. Since every character is an idempotent in the group algebra, `matrix_projection` is a projection (e.g. in the sense of linear algebra) in the fixed basis.
Character (as an idempotent) and `matrix_projection` (as matrix) play the same game as quadratic form and its matrix realization in classical linear algebra. 

`isotypical_basis` just finds a maximal set of independent vectors in the image of a projection. One could use `rref` for this, or SVD as I did here:
https://github.com/kalmarek/PropertyT.jl/blob/db044301059cecc3dfe7aa22325aa39e4109b981/src/blockdecomposition.jl#L28
_Isotypical_ refers to the fact that a representation may decompose into constitutents (~irreducible summands) with multiplicities (so called isotypical decomposition). The returned basis is a basis for the whole block of such type. 
Since characters (in the group algebra) are orthogonal, in the sense of this `dot`:
https://github.com/kalmarek/SymbolicWedderburn.jl/blob/5ec5eff1e6a11bd8e908e3b122fc5adb68cf608b/src/characters.jl#L5
(which is just a specialization of a general `dot` on the group algebra), the derived matrix projections are orthogonal (i.e. their images are orthogonal subspaces), so combining/concatenating their images gives you blocks of orthogonality.

**Comment by kalmarek** [comment]
Probably at a later stage we may opt to provide more thorough explanation in e.g. a case-study documentation as you do here:
https://jump.dev/SumOfSquares.jl/latest/generated/Symmetry%20reduction/

??

**Comment by blegat** [comment]
Thanks for the details!
So the primitive central idempotents of CG are `e_i = χ_i(1)/|G| * sum_g χ_i(inv(g)) * g` where χ_i are the characters of the irreps.
We drop the `χ_i(1)/|G|` as it's just constant and we compute instead `sum_g χ_i(g) * inv(g)`. The regular representation of `inv(g)` is the matrix with `i^g` in each row `i` which gives
https://github.com/kalmarek/SymbolicWedderburn.jl/blob/5ec5eff1e6a11bd8e908e3b122fc5adb68cf608b/src/projections.jl#L45-L51
since `val` is `χ_i(g)`, correct ?

> Probably at a later stage we may opt to provide more thorough explanation in e.g. a case-study documentation

Yes, it's a good idea. I do something similar in https://jump.dev/SumOfSquares.jl/latest/generated/Polynomial%20Optimization/#A-deeper-look-into-atom-extraction.

**Comment by kalmarek** [comment]
that's correct, with a small amendment, that it's not the regular representation (group acting by left/right multiplication on itself), but the representation given by the action of the group on the basis.

In our case we have `π:G → GL(basis)` and to obtain projections for central idempotents (~characters) one need to evaluate the action matrix for each element `g∈G`. (yes, I forgot about `g⁻¹` above).

For matrix groups precisely this function needs to be extended.

**Comment by blegat** [comment]
Thanks, that clarifies it :)
